### PR TITLE
Add support for WS2812 LED strips

### PR DESCRIPTION
**Pull request by aykevl**
Could be better, but it's a start. With a simple rainbow animation:

Screenshot at 2019-12-14 16-57-52

### CODE REVIEW

**Comment by aykevl** [comment]
Note: updated the PR slightly because I had accidentally swapped two colors and to hopefully make the colors a bit more correct.

**Comment by deadprogram** [comment]
Switched to a new `dev` branch just so we can have more discrete control over deployment, even though this PR probably works with the current release.

Merging.

**Comment by aykevl** [comment]
> Switched to a new `dev` branch just so we can have more discrete control over deployment, even though this PR probably works with the current release.

It does not, it depends on https://github.com/tinygo-org/drivers/pull/105 to work.

**Comment by deadprogram** [comment]
Both PR were merged into `dev` branch in their respective repos. So they are ready for our next release.

**Pull request merged**
